CREATE TABLE BRANDS
(
    ID   INT PRIMARY KEY,
    NAME VARCHAR(100) NOT NULL
);

CREATE TABLE PRICES
(
    BRAND_ID   INT,
    START_DATE TIMESTAMP,
    END_DATE   TIMESTAMP,
    PRICE_LIST INT            NOT NULL,
    PRODUCT_ID INT            NOT NULL,
    PRIORITY   INT DEFAULT 0,
    PRICE      DECIMAL(10, 2) NOT NULL,
    CURR       CHAR(3)        NOT NULL,
    PRIMARY KEY (PRICE_LIST, PRODUCT_ID, START_DATE),
    FOREIGN KEY (BRAND_ID) REFERENCES BRANDS (ID)
);
